biomes:
  - DEFAULT
materials:
  OAK_SAPLING:
    oak8:
      weight: 40
      y-offset: -3
    oak10:
      weight: 60
      y-offset: -1
    oak6:
      weight: 26
      y-offset: -2
    oak5:
      weight: 60
      y-offset: -1
    oak4:
      weight: 34
      y-offset: -2
  BIRCH_SAPLING:
    birch1:
      weight: 85
      y-offset: -1
    birch2:
      weight: 70
      y-offset: -3
    birch4:
      weight: 75
      y-offset: -1
    birch5:
      weight: 38
      y-offset: -2
      x-offset: -1
    birch3:
      weight: 43
      y-offset: -3
  SPRUCE_SAPLING:
    spruce3:
      weight: 25
      y-offset: -1
    spruce4:
      weight: 50
    spruce1:
      weight: 60
    spruce2:
      weight: 80
      y-offset: -1
    spruce5:
      weight: 60
      y-offset: -1
  JUNGLE_SAPLING:
    jungle5:
      weight: 70
    jungle4:
      weight: 60
    jungle2:
      weight: 68
    jungle3:
      weight: 10
      y-offset: -2
    jungle1:
      weight: 65
  ACACIA_SAPLING:
    acacia1L:
      weight: 30
      y-offset: -4
    acacia1M:
      weight: 70
      y-offset: -2
    acacia1S:
      weight: 100
      y-offset: -1
    acacia2L:
      weight: 33
  DARK_OAK_SAPLING:
    dark-oak1:
      weight: 90
      y-offset: -4
    dark-oak2:
      weight: 72
      y-offset: -2
    dark-oak3:
      weight: 70
      y-offset: -2
    dark-oak4:
      weight: 60
      y-offset: -3
  BROWN_MUSHROOM:
    B6:
      weight: 65
  RED_MUSHROOM:
    R7:
      weight: 100
    W4:
      weight: 50
  WARPED_FUNGUS:
    deadbush:
      weight: 100
  CRIMSON_FUNGUS:
    deadbush:
      weight: 100
