author: multitallented
database: false
description: Makes saplings and mushrooms grow into worldedit schematics
main: org.redcastlemedia.bukkit.customtrees.CustomTrees
name: CustomTrees
load: POSTWORLD
version: 1.0-SNAPSHOT
api-version: 1.14